### ISSUE TITLE
Windows support (project migrated from Xamarin using Redth/ZXing.Net.Mobile)

### ISSUE THREAD

**Issue by SunshineSpring666** [Redth/ZXing.Net.Maui#26]
Hi Redth,
     ZXing.Net.Mobile is awesome! 
     My project was migrated from Xamarin to MAUI recently. But when testing it on Windows, 
the page which contains the ZXing.Net.Maui barcode reader shows "Not Supported". Could you please support WinUI so it covers desktop scenarios?

**Comment by Redth** [comment]
There's really no easy solution to implementing this on Windows currently since `CaptureElement` is not yet supported in Windows App SDK.

It may be possible to do a [bunch of pinvokes and use directshow](https://github.com/castorix/WinUI3_DirectShow_Capture) to capture the camera's frames, but this is not work I'm currently planning on tackling.  If someone else wants to attempt a PR using DirectShow, that could be interesting.

**Comment by SunshineSpring666** [comment]
Thanks, Redth.  may dig into the directshow if time permits.
Best Regards

**Comment by veikkoeeva** [comment]
There is this DirectShow code at https://github.com/castorix/WinUI3_DirectShow_Capture by @castorix and some and CaptureElement in C# by @rgomez90 a https://github.com/microsoft/microsoft-ui-xaml/issues/4710#issuecomment-1017092342.

I add these since they may be of general interest here.

**Comment by baaaaif** [comment]
Solution from @paoldev works like a charm. Thx 💯
